language: ruby
cache:
  - bundler
install:
  - bundle install
rvm:
  - 2.1
  - 2.2.1
  - 2.3.0

script:
  - bundle exec rake default
  - gem build sensu-plugins-kafka.gemspec
  - gem install sensu-plugins-kafka-*.gem
